Разбивка компонента «Конструктор пиццы» на мелкие компоненты
htmlacademy-vue/1848573-pizza-1 pull request #2
Opened 2022-04-20 17:50 UTC by platonov

---
:mortar_board: [Разбивка компонента «Конструктор пиццы» на мелкие компоненты](https://up.htmlacademy.ru/vue/1/user/1848573/tasks/3)

2022-04-21 17:50 UTC, xyz27900 requested changes

2022-04-21 17:50 UTC, xyz27900 commented on src/frontend/src/layouts/AppLayout.vue
> +import AppLayoutHeader from "./AppLayoutHeader.vue";
хорошей практикой будет везде писать абсолютные пути от корня (@)

2022-04-21 17:50 UTC, xyz27900 commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      <a href="cart.html">0 ₽</a>
Стоит считать цену здесь

2022-04-23 06:12 UTC, platonov commented on src/frontend/src/layouts/AppLayout.vue
> +import AppLayoutHeader from "./AppLayoutHeader.vue";
поправил

2022-04-25 16:09 UTC, platonov commented on src/frontend/src/layouts/AppLayout.vue
> +import AppLayoutHeader from "./AppLayoutHeader.vue";
> хорошей практикой будет везде писать абсолютные пути от корня (@)

надо отправить на проверку повторно ?

2022-04-27 17:35 UTC, xyz27900 commented on src/frontend/src/layouts/AppLayout.vue
> +import AppLayoutHeader from "./AppLayoutHeader.vue";
ага, извини за задержку

2022-04-27 17:35 UTC, xyz27900 approved these changes

2022-04-27 17:36 UTC, merged